## 기업 개황(Overview): 여러 회사
+ 작성: 임경호
+ 금융감독원 OPEN DART https://opendart.fss.or.kr/

In [6]:
from tqdm import tqdm
from time import sleep
import requests
import pandas as pd

# Company Info   
url = 'https://opendart.fss.or.kr/api/company.json'
api_key = 'f2e08d4ed3de0ba3d5cbf59c04c223e02b1751a2'

corp_codes = [
    '00449069',
    '00351995',
]

corp_list = []
for corp_code in tqdm(corp_codes):
    sleep(0.1)
    params = {
        'corp_code': corp_code,
        'crtfc_key': api_key,
    }
    try:
        response = requests.get(url, params=params)     
        if response.status_code == 200:     # URL GET '200 정상'
            json_data = response.json()
            if json_data['status'] == '020':    # 사용한도 초과
                print(json_data['message'])
                raise Exception
            else:
                corp_list.append(json_data)
        else:
            print("URL GET Error", corp_code)
            break
    except Exception as e:
        print(e)
        break

df_corp_info = pd.DataFrame(corp_list)

100%|██████████| 2/2 [00:00<00:00,  3.72it/s]

In [7]:
df_corp_info

,status,message,corp_code,corp_name,corp_name_eng,stock_name,stock_code,ceo_nm,corp_cls,jurir_no,bizr_no,adres,hm_url,ir_url,phn_no,fax_no,induty_code,est_dt,acc_mt
0,000,정상,00449069,(주)지에스이,"GSE Co.,Ltd.",지에스이,,유석형,E,1912110009550,6138130629,경상남도 사천시 사천읍 장전리 877,www.yesgse.com,,055-855-0100,055-855-0109,35200,20030101,12
1,000,정상,00351995,(주)지에스이,"GSE Co., Ltd.",지에스이,053050,유석형,K,1101110624969,1058137529,경상남도 사천시 사천읍 구암두문로 412-30,www.yesgse.com,www.yesgse.com,055-855-0102,055-855-0107,35200,19890421,12