### 인덱스 가격

### FinanceDataReader
- pip install -U finance-datareader
- 사용자 안내서: https://financedata.github.io/posts/finance-data-reader-users-guide.html#
#### 종목 코드
- 거래소별 전체 종목코드: KRX (KOSPI, KODAQ, KONEX), NASDAQ, NYSE, AMEX, S&P 500
#### 가격 데이터
- 해외주식 가격 데이터: AAPL(애플), AMZN(아마존), GOOG(구글) 등
- 국내주식 가격 데이터: 005930(삼성전자), 091990(셀트리온헬스케어) 등
- 각종 지수: KS11(코스피지수), KQ11(코스닥지수), DJI(다우지수), IXIC(나스닥 지수), US500(S&P 5000)
- 환율 데이터: USD/KRX (원달러 환율), USD/EUR(달러당 유로화 환율), CNY/KRW: 위엔화 원화 환율
- 암호화폐 가격: BTC/USD (비트코인 달러 가격, Bitfinex), BTC/KRW (비트코인 원화 가격, 빗썸)

In [8]:
# 네이버 금융
import FinanceDataReader as fdr

index_code = 'KS11'     # KOSPI
start_date = '2023-08-21'
end_date = '2023-08-31'

df_fdr = fdr.DataReader(index_code, start=start_date, end=end_date)
df_fdr

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2023-08-21,2511.699951,2524.409912,2505.590088,2508.800049,2508.800049,398600
2023-08-22,2528.389893,2533.429932,2509.530029,2515.739990,2515.739990,471000
2023-08-23,2510.000000,2517.510010,2499.889893,2505.500000,2505.500000,546200
2023-08-24,2531.780029,2539.439941,2520.729980,2537.679932,2537.679932,440300
2023-08-25,2505.389893,2526.370117,2502.050049,2519.139893,2519.139893,576400
2023-08-28,2519.139893,2543.409912,2519.139893,2543.409912,2543.409912,483000
2023-08-29,2550.760010,2556.979980,2545.270020,2552.159912,2552.159912,440700
2023-08-30,2575.419922,2578.620117,2561.219971,2561.219971,2561.219971,363000