In [26]:
key = "YTg2NjFjM2FkOGFjZWQ5ODBmMDY1M2IwZTZiNjRlNzg="
url = "https://kosis.kr/openapi/statisticsList.do?method=getList"   # 요청 URL

In [27]:
service_view = "MT_ZTITLE"

In [28]:
import requests
import warnings
warnings.filterwarnings('ignore')

params ={'apiKey' : key,           # 발급된 인증 key
        'vwCd' : service_view,     # 서비스뷰 코드
        'parentId' : "A",          # 시작목록 ID
        "jsonVD" : "Y",            # 결과 유형이 "json"인 경우 필수
        'format' : "json"          # 결과 유형
        }

response = requests.get(url, params=params, verify=False)

if response.status_code == 200:     # URL GET '200 정상'
    print("URL GET Successful")
    
if response.text.__contains__("err"):
    print("No Data", response.text)

URL GET Successful

In [30]:
import json
contents = response.text  
json_data = json.loads(contents)
df = pd.DataFrame(json_data)

In [31]:
df

     LIST_NM      VW_CD     VW_NM LIST_ID
0         인구  MT_ZTITLE  국내통계 주제별       A
1       사회일반  MT_ZTITLE  국내통계 주제별       B
2      범죄ㆍ안전  MT_ZTITLE  국내통계 주제별       C
3         노동  MT_ZTITLE  국내통계 주제별       D
4   소득ㆍ소비ㆍ자산  MT_ZTITLE  국내통계 주제별       E
5         보건  MT_ZTITLE  국내통계 주제별       F
6         복지  MT_ZTITLE  국내통계 주제별       G
7      교육ㆍ훈련  MT_ZTITLE  국내통계 주제별      H1
8      문화ㆍ여가  MT_ZTITLE  국내통계 주제별      H2
9         주거  MT_ZTITLE  국내통계 주제별      I1
10      국토이용  MT_ZTITLE  국내통계 주제별      I2
11   경제일반ㆍ경기  MT_ZTITLE  국내통계 주제별      J1
12      기업경영  MT_ZTITLE  국내통계 주제별      J2
13        농림  MT_ZTITLE  국내통계 주제별      K1
14        수산  MT_ZTITLE  국내통계 주제별      K2
15    광업ㆍ제조업  MT_ZTITLE  국내통계 주제별       L
16        건설  MT_ZTITLE  국내통계 주제별      M1
17     교통ㆍ물류  MT_ZTITLE  국내통계 주제별      M2
18      정보통신  MT_ZTITLE  국내통계 주제별      N1
19     과학ㆍ기술  MT_ZTITLE  국내통계 주제별      N2
20   도소매ㆍ서비스  MT_ZTITLE  국내통계 주제별       O
21        임금  MT_ZTITLE  국내통계 주제별      P1
22        물가  MT_ZTITLE  국내통계 주제별      P2
23      국민계정  MT_ZTITLE  국내통계 주제별       Q
24     정부ㆍ재정  MT_ZTITLE  국내통계 주제별       R
25        금융  MT_ZTITLE  국내통계 주제별      S1
26   무역ㆍ국제수지  MT_ZTITLE  국내통계 주제별      S2
27        환경  MT_ZTITLE  국내통계 주제별       T
28       에너지  MT_ZTITLE  국내통계 주제별       U
29      지역통계  MT_ZTITLE  국내통계 주제별       V