### 사업보고서 "재무제표 주석" 문서 URL 전체 목록과 사업보고서 목록과 Cross-check

In [1]:
import pandas as pd
# 데이터 Loading
path_dir1 = "D:/PythonProject/data-gatherer/dart_fs_notes/fs_notes/"
df1 = pd.read_csv(path_dir1 + 'fs_notes_all.csv', dtype=object)
path_dir2 = "D:/PythonProject/data-gatherer/dart_fs_notes/items/"
df2 = pd.read_csv(path_dir2 + 'items_all.csv', dtype=object)

In [2]:
# df2에 있는 corp_code 목록에 해당하는 df1의 목록을 설정
corp_codes = df2.loc[(df2.corp_cls == 'Y') & (df2.rpt_name.str[-8:-4] >= '2017') & (df2.rpt_name.str[-8:-4] <= '2021'), ]['corp_code'].unique()
df1 = df1[df1['corp_code'].isin(corp_codes)]

In [4]:
# dart_rpt_all(df1)에는 있으나 fs_notes_all(df2)에는 데이터가 빠져있는 목록
df_missing = pd.merge(df1, df2, how='outer', left_on='rpt_num', right_on='rpt_num' , indicator=True).query("_merge=='left_only'")

In [5]:
df_missing.columns

Index(['corp_code_x', 'stock_code_x', 'corp_cls_x', 'corp_name_x', 'rpt_num',
       'rpt_name_x', 'rpt_url', 'doc_title_x', 'doc_url', 'doc_result_x',
       'corp_code_y', 'stock_code_y', 'corp_cls_y', 'corp_name_y',
       'rpt_name_y', 'doc_title_y', 'doc_result_y', 'unit', 'val_a', 'val_b',
       'item_result', '_merge'],
      dtype='object')

In [7]:
df_missing.sort_values(by=['corp_code_x', 'rpt_num'])

,corp_code_x,stock_code_x,corp_cls_x,corp_name_x,rpt_num,rpt_name_x,rpt_url,doc_title_x,doc_url,doc_result_x,...,corp_cls_y,corp_name_y,rpt_name_y,doc_title_y,doc_result_y,unit,val_a,val_b,item_result,_merge
61,00112022,024890,Y,대원화성,20170331001688,사업보고서 (2016.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
62,00112022,024890,Y,대원화성,20180402001524,사업보고서 (2017.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
63,00112022,024890,Y,대원화성,20210506000552,[기재정정]사업보고서 (2019.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [9]:
df1[df1['corp_code'] == '00112022']

,corp_code,stock_code,corp_cls,corp_name,rpt_num,rpt_name,rpt_url,doc_title,doc_url,doc_result
117,00112022,024890,Y,대원화성,20170331001688,사업보고서 (2016.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
118,00112022,024890,Y,대원화성,20180402001524,사업보고서 (2017.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
119,00112022,024890,Y,대원화성,20210506000552,[기재정정]사업보고서 (2019.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
120,00112022,024890,Y,대원화성,20210506000547,[기재정정]사업보고서 (2018.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
121,00112022,024890,Y,대원화성,20210507000170,[기재정정]사업보고서 (2020.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
122,00112022,024890,Y,대원화성,20220816001036,[기재정정]사업보고서 (2021.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK
123,00112022,024890,Y,대원화성,20230316001139,사업보고서 (2022.12),http://dart.fss.or.kr/dsaf001/main.do?rcpNo=20...,5. 재무제표 주석,http://dart.fss.or.kr/report/viewer.do?rcpNo=2...,OK

In [10]:
df2[df2['corp_code'] == '00112022']

,corp_code,stock_code,corp_cls,corp_name,rpt_num,rpt_name,doc_title,doc_result,unit,val_a,val_b,item_result
61,00112022,024890,Y,대원화성,20210507000170,[기재정정]사업보고서 (2020.12),5. 재무제표 주석,OK,천원,0.0,0.0,OK
62,00112022,024890,Y,대원화성,20220816001036,[기재정정]사업보고서 (2021.12),5. 재무제표 주석,OK,천원,0.0,0.0,OK
63,00112022,024890,Y,대원화성,20210506000547,[기재정정]사업보고서 (2018.12),5. 재무제표 주석,OK,천원,0.0,0.0,OK
64,00112022,024890,Y,대원화성,20230316001139,사업보고서 (2022.12),5. 재무제표 주석,OK,천원,0.0,0.0,OK